### ISSUE TITLE
Move the nutrition tracker code from the Demo repo to the UI Module repo

### ISSUE THREAD

**Issue by marinPassio** [Passiolife/Passio-Nutrition-AI-iOS-UI-Module#1]
- [x] Move all of the code containing the nutrition tracker features starting with the Dashboard screen from the Demo App to the UI Module repo (this repo)
- [x] Organize the UI Module code  in a way that it can be shipped as Swift package
- [x] The API of the UI Module will contain a start method along with the ability to add a specific implementation of the `PassioConnector` protocol 
- [x] The Demo App (private repo) will contain the user authentication logic, engineering views and will use the UI Module package as a dependency
- [x] The SDK should be configured within the Demo App
- [x] Write a small readme file detailing the setup of the UI Module once it's imported into another app
- [x] Investigate how to ship the dependencies of the UI Module with the package (worst case scenario the implementing app will have to add them manually)
